alias gems='cd `rvm gemdir`'

alias sc='bundle exec rails console'
alias ss='bundle exec rails server'
alias sg='bundle exec rails generate'
alias sd='bundle exec rails destroy'
alias be='bundle exec'
alias tlog='tail -f log/development.log'
alias migrate='bundle exec rake db:migrate db:test:clone'
alias cuke='bundle exec cucumber'
alias diffspec='git diff master --name-only | grep _spec | xargs rspec'
