alias sc='rails console'
alias ss='rails server'
alias sg='rails generate'
alias sd='rails destroy'
alias be='bundle exec'
alias tlog='tail -f log/development.log'
alias diffspec='git diff master --name-only | grep _spec | xargs rspec'
